# Netlify Functions v2 (ESM)
[build]
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"

# Cron job - nettoyage des orders pending coincés
[functions."scheduled-cleanup-pending"]
  schedule = "0 3 * * *"  # 3h du matin tous les jours